addons:
  postgresql: 11.1
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database PKShoes_test;' -U postgres
dist: trusty
language: ruby
rvm:
  - 2.5.3
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake test